"use client";
import {useEffect,useMemo,useState} from "react";import {MapPin,Navigation,Radio,Tent,Users} from "lucide-react";import {supabase} from "../lib/supabase";import {bearing,direction,distance,Point} from "../lib/geo";
type Tab="radar"|"people"|"places";type Peer={user_id:string;nickname:string;latitude:number;longitude:number;accuracy?:number;updated_at?:string};
export default function Home(){const[tab,setTab]=useState<Tab>("radar"),[userId,setUserId]=useState(""),[nickname,setNickname]=useState(""),[draft,setDraft]=useState(""),[group,setGroup]=useState<any>(null),[code,setCode]=useState(""),[me,setMe]=useState<(Point&{accuracy?:number})|null>(null),[peers,setPeers]=useState<Peer[]>([]),[target,setTarget]=useState<Peer|null>(null),[tent,setTent]=useState<Point|null>(null),[heading,setHeading]=useState(0),[error,setError]=useState("");
useEffect(()=>{(async()=>{let{data:{session}}=await supabase.auth.getSession();if(!session){const r=await supabase.auth.signInAnonymously();session=r.data.session;if(r.error)setError("Ative o acesso anônimo no Supabase Auth.");}if(session){setUserId(session.user.id);const p=await supabase.from("profiles").select("nickname").eq("user_id",session.user.id).maybeSingle();if(p.data?.nickname)setNickname(p.data.nickname);const t=await supabase.from("saved_places").select("latitude,longitude").eq("user_id",session.user.id).eq("kind","tent").maybeSingle();if(t.data)setTent(t.data as Point)}})()},[]);
useEffect(()=>{if(!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>setMe({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),e=>setError("Precisamos da sua localização para o radar funcionar."),{enableHighAccuracy:true,maximumAge:4000,timeout:15000});return()=>navigator.geolocation.clearWatch(id)},[]);
useEffect(()=>{const fn=(e:any)=>{const h=e.webkitCompassHeading??(e.alpha!=null?360-e.alpha:null);if(h!=null)setHeading(h)};window.addEventListener("deviceorientation",fn,true);return()=>window.removeEventListener("deviceorientation",fn,true)},[]);
useEffect(()=>{if(!userId||!me)return;const id=setTimeout(()=>supabase.from("last_locations").upsert({user_id:userId,...me,heading,updated_at:new Date().toISOString()}),1200);return()=>clearTimeout(id)},[userId,me,heading]);
useEffect(()=>{if(!group||!userId)return;const load=async()=>{const m=await supabase.from("group_members").select("user_id").eq("group_id",group.id);const ids=(m.data||[]).map(x=>x.user_id).filter(x=>x!==userId);if(!ids.length){setPeers([]);return}const[p,l]=await Promise.all([supabase.from("profiles").select("user_id,nickname").in("user_id",ids),supabase.from("last_locations").select("*").in("user_id",ids)]);setPeers((l.data||[]).map((x:any)=>({...x,nickname:p.data?.find((z:any)=>z.user_id===x.user_id)?.nickname||"Pessoa"})))};load();const timer=setInterval(load,6000);return()=>clearInterval(timer)},[group,userId]);
const destination=target||tent;const nav=useMemo(()=>me&&destination?{d:distance(me,destination),b:bearing(me,destination)}:null,[me,destination]);
async function saveName(){if(draft.trim().length<2)return;await supabase.from("profiles").upsert({user_id:userId,nickname:draft.trim(),updated_at:new Date().toISOString()});setNickname(draft.trim())}
async function createGroup(){const join=Math.random().toString(36).slice(2,8).toUpperCase();const g=await supabase.from("groups").insert({name:"Meu acampamento",join_code:join,owner_id:userId}).select().single();if(g.data){await supabase.from("group_members").insert({group_id:g.data.id,user_id:userId});setGroup(g.data)}}
async function joinGroup(){const g=await supabase.from("groups").select("*").eq("join_code",code.trim().toUpperCase()).maybeSingle();if(!g.data){setError("Grupo não encontrado.");return}const r=await supabase.from("group_members").insert({group_id:g.data.id,user_id:userId});if(!r.error)setGroup(g.data);else setError("Não foi possível entrar neste grupo.")}
async function markTent(){if(!me)return setError("Aguardando GPS.");await supabase.from("saved_places").upsert({user_id:userId,kind:"tent",label:"Minha barraca",latitude:me.latitude,longitude:me.longitude,accuracy:me.accuracy,updated_at:new Date().toISOString()},{onConflict:"user_id"});setTent(me);setTarget(null);setTab("radar")}
if(!nickname)return <main className="shell"><div className="top"><div className="brand">EarthDance Radar</div></div><section className="hero"><Radio size={42}/><p className="eyebrow">Seu ponto de encontro</p><h1 className="big">Como podemos te chamar?</h1><p className="muted">Sem e-mail, sem senha. Só um nome para sua galera te reconhecer.</p></section><div className="card"><input className="input" placeholder="Seu nome ou apelido" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="btn" style={{width:"100%"}} onClick={saveName}>Entrar no radar</button>{error&&<p className="error">{error}</p>}</div></main>;
if(!group)return <main className="shell"><div className="top"><div className="brand">EarthDance Radar</div><span className="live">● {me?"GPS ativo":"GPS..."}</span></div><section className="hero"><p className="eyebrow">Olá, {nickname}</p><h1 className="big">Encontre sua galera.</h1><p className="muted">Crie um acampamento ou entre com o código dos seus amigos.</p></section><div className="card"><button className="btn" style={{width:"100%"}} onClick={createGroup}>Criar meu grupo</button></div><div className="card"><input className="input" placeholder="Código do grupo" value={code} onChange={e=>setCode(e.target.value)}/><button className="btn secondary" style={{width:"100%"}} onClick={joinGroup}>Entrar no grupo</button></div>{error&&<p className="error">{error}</p>}</main>;
return <main className="shell"><div className="top"><div><div className="brand">EarthDance Radar</div><div className="muted">Grupo {group.join_code}</div></div><span className="live">● {me?"GPS ativo":"GPS..."}</span></div>{tab==="radar"&&<><section className="hero"><p className="eyebrow">{target?target.nickname:tent?"Minha barraca":"Radar pronto"}</p><div className="radar"><div className="pulse"><span className="arrow" style={{transform:`rotate(${nav?nav.b-heading:0}deg)`}}>↑</span></div></div>{nav?<><div className="metric">{nav.d<1000?Math.round(nav.d)+" m":(nav.d/1000).toFixed(1)+" km"}</div><p className="muted">Direção {direction(nav.b)} · GPS {me?.accuracy?"±"+Math.round(me.accuracy)+" m":""}</p></>:<><div className="big">Escolha um destino</div><p className="muted">Selecione uma pessoa ou marque sua barraca.</p></>}</section><div className="card row"><div><Tent size={20}/><b> Minha barraca</b><div className="muted">{tent?"Local salvo":"Ainda não marcada"}</div></div><button className="btn secondary" onClick={tent?()=>{setTarget(null)}:markTent}>{tent?"Encontrar":"Marcar"}</button></div></>}{tab==="people"&&<><section className="hero" style={{paddingBottom:8}}><p className="eyebrow">Seu grupo</p><h2 className="big">Pessoas próximas</h2></section><div className="list">{peers.length?peers.map(p=><div className="person row" key={p.user_id}><div><b><span className="dot"/>{p.nickname}</b><div className="muted">{me?Math.round(distance(me,p))+" m de você":"Aguardando GPS"}</div></div><button className="btn secondary" onClick={()=>{setTarget(p);setTab("radar")}}>Encontrar</button></div>):<div className="card"><b>Ninguém apareceu ainda.</b><p className="muted">Compartilhe o código <b>{group.join_code}</b> com sua galera.</p></div>}</div></>}{tab==="places"&&<><section className="hero" style={{paddingBottom:8}}><p className="eyebrow">Pontos salvos</p><h2 className="big">Seu acampamento</h2></section><div className="card"><MapPin/><h3>Minha barraca</h3><p className="muted">{tent?"Coordenadas salvas neste aparelho e na sua conta anônima.":"Marque a posição quando estiver ao lado da barraca."}</p><button className="btn" onClick={markTent}>{tent?"Atualizar posição":"Marcar barraca aqui"}</button></div></>}<nav className="nav"><button className={tab==="radar"?"active":""} onClick={()=>setTab("radar")}><Navigation size={18}/><br/>Radar</button><button className={tab==="people"?"active":""} onClick={()=>setTab("people")}><Users size={18}/><br/>Pessoas</button><button className={tab==="places"?"active":""} onClick={()=>setTab("places")}><Tent size={18}/><br/>Barraca</button></nav>{error&&<p className="error">{error}</p>}</main>}